/// Flutter icons MiAlbumIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MiAlbumIcons
///      fonts:
///       - asset: fonts/MiAlbumIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MiAlbumIcons {
  MiAlbumIcons._();

  static const _kFontFam = 'MiAlbumIcons';
  static const String? _kFontPkg = null;

  static const IconData pappIcon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
