import {
  Album,
  Figure,
  FigureCategory,
  FigurePrefix,
  FigureSection,
  FigureType,
  OwnerRol,
} from '@pappcorn/mialbum/util-interfaces';

export function generateNewAlbum(
  userId: string,
  name: string,
  key: string
): Album {
  return {
    name,
    dates: {
      start: new Date().getTime(),
      lastUpdate: new Date().getTime(),
    },
    managers: {
      [userId]: OwnerRol.CREATOR,
    },
    key,
    owner: userId,
    figures: generateNewAlbumFigures(),
  };
}

export function generateNewAlbumFigures(): Figure[] {
  return [
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.EMBLEM,
      prefix: FigurePrefix.FWC,
      number: 0,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.EMBLEM,
      prefix: FigurePrefix.FWC,
      number: 1,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.EMBLEM,
      prefix: FigurePrefix.FWC,
      number: 2,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.EMBLEM,
      prefix: FigurePrefix.FWC,
      number: 3,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.EMBLEM,
      prefix: FigurePrefix.FWC,
      number: 4,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.EMBLEM,
      prefix: FigurePrefix.FWC,
      number: 5,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.EMBLEM,
      prefix: FigurePrefix.FWC,
      number: 6,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.EMBLEM,
      prefix: FigurePrefix.FWC,
      number: 7,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.STADIUM,
      prefix: FigurePrefix.FWC,
      number: 8,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.STADIUM,
      prefix: FigurePrefix.FWC,
      number: 9,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.STADIUM,
      prefix: FigurePrefix.FWC,
      number: 10,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.STADIUM,
      prefix: FigurePrefix.FWC,
      number: 11,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.STADIUM,
      prefix: FigurePrefix.FWC,
      number: 12,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.STADIUM,
      prefix: FigurePrefix.FWC,
      number: 13,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.STADIUM,
      prefix: FigurePrefix.FWC,
      number: 14,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.STADIUM,
      prefix: FigurePrefix.FWC,
      number: 15,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.STADIUM,
      prefix: FigurePrefix.FWC,
      number: 16,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.STADIUM,
      prefix: FigurePrefix.FWC,
      number: 17,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.STADIUM,
      prefix: FigurePrefix.FWC,
      number: 18,
    },
    ...newTeam(FigureCategory.GROUP_A, FigurePrefix.QAT),
    ...newTeam(FigureCategory.GROUP_A, FigurePrefix.ECU),
    ...newTeam(FigureCategory.GROUP_A, FigurePrefix.SEN),
    ...newTeam(FigureCategory.GROUP_A, FigurePrefix.NED),
    ...newTeam(FigureCategory.GROUP_B, FigurePrefix.ENG),
    ...newTeam(FigureCategory.GROUP_B, FigurePrefix.IRN),
    ...newTeam(FigureCategory.GROUP_B, FigurePrefix.USA),
    ...newTeam(FigureCategory.GROUP_B, FigurePrefix.WAL),
    ...newTeam(FigureCategory.GROUP_C, FigurePrefix.ARG),
    ...newTeam(FigureCategory.GROUP_C, FigurePrefix.KSA),
    ...newTeam(FigureCategory.GROUP_C, FigurePrefix.MEX),
    ...newTeam(FigureCategory.GROUP_C, FigurePrefix.POL),
    ...newTeam(FigureCategory.GROUP_D, FigurePrefix.FRA),
    ...newTeam(FigureCategory.GROUP_D, FigurePrefix.AUS),
    ...newTeam(FigureCategory.GROUP_D, FigurePrefix.DEN),
    ...newTeam(FigureCategory.GROUP_D, FigurePrefix.TUN),
    ...newTeam(FigureCategory.GROUP_E, FigurePrefix.ESP),
    ...newTeam(FigureCategory.GROUP_E, FigurePrefix.CRC),
    ...newTeam(FigureCategory.GROUP_E, FigurePrefix.GER),
    ...newTeam(FigureCategory.GROUP_E, FigurePrefix.JPN),
    ...newTeam(FigureCategory.GROUP_F, FigurePrefix.BEL),
    ...newTeam(FigureCategory.GROUP_F, FigurePrefix.CAN),
    ...newTeam(FigureCategory.GROUP_F, FigurePrefix.MAR),
    ...newTeam(FigureCategory.GROUP_F, FigurePrefix.CRO),
    ...newTeam(FigureCategory.GROUP_G, FigurePrefix.BRA),
    ...newTeam(FigureCategory.GROUP_G, FigurePrefix.SRB),
    ...newTeam(FigureCategory.GROUP_G, FigurePrefix.SUI),
    ...newTeam(FigureCategory.GROUP_G, FigurePrefix.CMR),
    ...newTeam(FigureCategory.GROUP_H, FigurePrefix.POR),
    ...newTeam(FigureCategory.GROUP_H, FigurePrefix.GHA),
    ...newTeam(FigureCategory.GROUP_H, FigurePrefix.URU),
    ...newTeam(FigureCategory.GROUP_H, FigurePrefix.KOR),
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.FIFA_MUSEUM,
      prefix: FigurePrefix.FWC,
      number: 19,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.FIFA_MUSEUM,
      prefix: FigurePrefix.FWC,
      number: 20,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.FIFA_MUSEUM,
      prefix: FigurePrefix.FWC,
      number: 21,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.FIFA_MUSEUM,
      prefix: FigurePrefix.FWC,
      number: 22,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.FIFA_MUSEUM,
      prefix: FigurePrefix.FWC,
      number: 23,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.FIFA_MUSEUM,
      prefix: FigurePrefix.FWC,
      number: 24,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.FIFA_MUSEUM,
      prefix: FigurePrefix.FWC,
      number: 25,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.FIFA_MUSEUM,
      prefix: FigurePrefix.FWC,
      number: 26,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.FIFA_MUSEUM,
      prefix: FigurePrefix.FWC,
      number: 27,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.FIFA_MUSEUM,
      prefix: FigurePrefix.FWC,
      number: 28,
    },
    {
      section: FigureSection.FIFA,
      checked: false,
      category: FigureCategory.FIFA_MUSEUM,
      prefix: FigurePrefix.FWC,
      number: 29,
    },
    {
      section: FigureSection.COCA_COLA,
      checked: false,
      category: FigureCategory.TEAM_BELIEVERS,
      prefix: FigurePrefix.C,
      number: 1,
    },
    {
      section: FigureSection.COCA_COLA,
      checked: false,
      category: FigureCategory.TEAM_BELIEVERS,
      prefix: FigurePrefix.C,
      number: 2,
    },
    {
      section: FigureSection.COCA_COLA,
      checked: false,
      category: FigureCategory.TEAM_BELIEVERS,
      prefix: FigurePrefix.C,
      number: 3,
    },
    {
      section: FigureSection.COCA_COLA,
      checked: false,
      category: FigureCategory.TEAM_BELIEVERS,
      prefix: FigurePrefix.C,
      number: 4,
    },
    {
      section: FigureSection.COCA_COLA,
      checked: false,
      category: FigureCategory.TEAM_BELIEVERS,
      prefix: FigurePrefix.C,
      number: 5,
    },
    {
      section: FigureSection.COCA_COLA,
      checked: false,
      category: FigureCategory.TEAM_BELIEVERS,
      prefix: FigurePrefix.C,
      number: 6,
    },
    {
      section: FigureSection.COCA_COLA,
      checked: false,
      category: FigureCategory.TEAM_BELIEVERS,
      prefix: FigurePrefix.C,
      number: 7,
    },
    {
      section: FigureSection.COCA_COLA,
      checked: false,
      category: FigureCategory.TEAM_BELIEVERS,
      prefix: FigurePrefix.C,
      number: 8,
    },
  ];
}

function newTeam(category: FigureCategory, prefix: FigurePrefix): Figure[] {
  const teamArray: Figure[] = [];
  for (let number = 1; number < 20; number++) {
    teamArray.push({
      section: FigureSection.TEAM,
      checked: false,
      category,
      prefix,
      type: number === 1 ? FigureType.EMBLEM : FigureType.PLAYER,
      number,
    });
  }
  return teamArray;
}
