// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqw0xb_Fa3pcyUPu4VFrtPBvM6PNNiNog',
    appId: '1:124812028575:android:affbd8cc77a177cd8050aa',
    messagingSenderId: '124812028575',
    projectId: 'mialbum-dev',
    storageBucket: 'mialbum-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTycwCk7MBrXWNuShxyjdGwfSDlXGwaNk',
    appId: '1:124812028575:ios:ad9ee20afd7907418050aa',
    messagingSenderId: '124812028575',
    projectId: 'mialbum-dev',
    storageBucket: 'mialbum-dev.appspot.com',
    androidClientId:
        '124812028575-e3sasm0iq2j0a5gs45ph931jg20ln2lm.apps.googleusercontent.com',
    iosClientId:
        '124812028575-lrlfh1q4od8tjr3jmtsluqldecia5f1t.apps.googleusercontent.com',
    iosBundleId: 'com.pappcorn.mialbum',
  );
}
